name: '🚀 CD'
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.vscode/**'
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: maandr/github-actions/.github/workflows/cd-generate-image-tags.yaml@v3
    with:
      image: ghcr.io/${{ github.repository }}

  publish:
    needs: prepare
    uses: maandr/github-actions/.github/workflows/cd-ghcr.yaml@v3
    with:
      tags: ${{ needs.generate-image-tags.outputs.tags }}
      labels: ${{ needs.generate-image-tags.outputs.labels }}
    secrets:
      GHCR_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
