name: '🧪 CI'
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.vscode/**'
      - '.github/dependabot.yaml'
      - '.github/workflows/cd.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  node:
    uses: maandr/github-actions/.github/workflows/ci-node.yaml@v3
    with:
      node_version: '21.7.x'

  docker:
    uses: maandr/github-actions/.github/workflows/ci-docker-image.yaml@v3
    with:
      file: './Dockerfile'
      context: './'
